- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    user: "{{ ansible_user_id }}"
  pre_tasks:
  - name: Update cache (brew)
    community.general.homebrew:
      update_homebrew: yes
    when: ansible_distribution == 'MacOSX'
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tasks:
  # Install for Ubuntu
  - include: tasks/ubuntu/ssh.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - include: tasks/ubuntu/git.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - include: tasks/ubuntu/core.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - include: tasks/ubuntu/zsh.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - include: tasks/ubuntu/dotfiles.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - include: tasks/ubuntu/nvim.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  # Install for MacOSX
  - include: tasks/macos/docker.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/aws.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/ssh.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/git.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/zsh.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/node.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/rust.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/go.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/dotfiles.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/neovim.yml
    when: ansible_distribution == 'MacOSX'
  - include: tasks/macos/stream.yml
    when: ansible_distribution == 'MacOSX'
