- name: Install neovim (homebrew)
  community.general.homebrew:
    name: neovim
  tags:
  - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install vim-plug for neovim
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
  - neovim

- name: Install ripgrep (homebrew)
  community.general.homebrew:
    name: ripgrep
  tags:
    - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install fd (homebrew) 
  community.general.homebrew:
    name: fd
  tags:
    - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install typescript (npm -g)
  npm:
    name: typescript
    global: true
  tags:
    - neovim
    - ts
    - node

- name: Install typescript-language-server (npm -g)
  npm:
    name: typescript-language-server 
    global: true
  tags:
    - neovim
    - ts
    - node

- name: Install rust-analyzer (homebrew)
  community.general.homebrew:
    name: rust-analyzer
  tags:
    - neovim
    - rust
  when: ansible_distribution == 'MacOSX'

- name: Install vscode-eslint-language-server (npm -g)
  npm:
    name: vscode-langservers-extracted
    global: true
  tags:
    - eslint
    - neovim
    - ts
