- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop", "golang", "lsof", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "moreutils", "clangd"]

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]