- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: ["curl", "htop", "lsof", "ccache", "ninja-build", "i3", "dconf-editor", "pavucontrol", "ubuntu-mate-desktop"]

- name: Install Workflow Packages
  become: true
  apt:
    name: ["tmux", "fzf", "ripgrep"]

- name: Install Search Tools
  become: true
  apt:
    name: ["fzf", "ripgrep"]

- name: Install Python
  become: true
  apt:
    name: ["python3-pip"]

- name: Install node
  become: true
  apt:
    name: ["nodejs", "npm"]

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core
