- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
  tags:
  - node

- name: Setup .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
    create: yes
  tags:
  - node

- name: Install node
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - 14.20.0
  tags:
  - node

# - name: Install nvm
#   shell: >
#     curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
#     creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
#   tags:
#   - node

# - name: Install node and set version
#   become: true
#   become_user: root
#   shell: "source /root/.nvm/nvm.sh && nvm install 16" 
#   args:
#     executable: /bin/bash
#   tags:
#   - node

# - name: Install node and set version
#   become: true
#   become_user: root
#   shell: /home/sam/.nvm/nvm.sh install 16
#   tags:
#   - node

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags:
  - node

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
  - node

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - node
  - npm-path

# - name: Delete Prefix
#   shell: >
#     /bin/zsh -c "source ~/.nvm/nvm.sh && nvm use --delete-prefix v16.20.0 --silent"
#     creates=/home/{{ ansible_user_id }}/.nvm/alias
#   tags:
#     - node

# - name: Install N
#   npm:
#     name: n
#     global: yes
#   tags:
#     - node
#
# - name: Install correct version of Node
#   shell: n 16
#   tags:
#     - node


- name: Install Yarn
  npm:
    name: yarn
    global: yes
  tags:
    - node

- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags:
    - node

- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - node

- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
    - node

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
    - node
