# - name: Ensure .ssh directory exists.
#   file:
#     dest: "{{ dest_key | dirname }}"
#     mode: 0700
#     state: directory
# - name: Install ssh key
#   copy:
#     src: "{{ source_key }}"
#     dest: "{{ dest_key }}"
#     mode: 0600
# - name: Install ssh key public
#   copy:
#     src: "{{ source_key }}.pub"
#     dest: "{{ dest_key }}.pub"
#     mode: 0644
# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
#   ignore_errors: yes

- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  become_user: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"