- name: Install git (homebrew)
  community.general.homebrew:
    name: git
  tags:
  - git
  - git-personal
  when: ansible_distribution == 'MacOSX'

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "s.sinadinovic@icloud.com"
  tags:
  - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "s-sinadinovic"
  tags:
  - git-personal

- name: Install GitHub CLI (brew)
  community.general.homebrew:
    name: gh
  tags:
  - git
  - github
