- name: Install neovim (homebrew)
  community.general.homebrew:
    name: neovim
  tags:
  - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install vim-plug for neovim
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
  - neovim

- name: Install ripgrep (homebrew)
  community.general.homebrew:
    name: ripgrep
  tags:
    - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install fd (homebrew) 
  community.general.homebrew:
    name: fd
  tags:
    - neovim
  when: ansible_distribution == 'MacOSX'

- name: Install typescript (npm -g)
  npm:
    name: typescript
    global: true
  tags:
    - neovim
    - ts
    - node

- name: Install typescript-language-server (npm -g)
  npm:
    name: typescript-language-server 
    global: true
  tags:
    - neovim
    - ts
    - node

- name: Install lua-language-server (homebrew)
  community.general.homebrew:
    name: lua-language-server
  tags:
    - neovim
    - lua

- name: Install stylua (homebrew)
  community.general.homebrew:
    name: stylua
  tags:
    - neovim
    - lua

- name: Install rust-analyzer (homebrew)
  community.general.homebrew:
    name: rust-analyzer
  tags:
    - neovim
    - rust
  when: ansible_distribution == 'MacOSX'

- name: Install vscode-eslint-language-server (npm -g)
  npm:
    name: vscode-langservers-extracted
    global: true
  tags:
    - eslint
    - neovim
    - ts

- name: Tap ethereum/ethereum (homebrew)
  community.general.homebrew_tap:
    name: ethereum/ethereum
  tags:
    - neovim
    - solidity
    - ethereum

- name: Install solidity (homebrew)
  community.general.homebrew:
    name: solidity
  tags:
    - neovim
    - solidity
    - solc
    - ethereum

- name: Install solidity-language-server (npm)
  npm:
    name: solidity-language-server
    global: true
  tags:
    - neovim
    - solidity
    - solc
    - ethereum

- name: Tap omnisharp/omnisharp-roslyn (homebrew)
  community.general.homebrew_tap:
    name: omnisharp/omnisharp-roslyn
  tags:
    - neovim
    - omnisharp
    - csharp

- name: Install Omnisharp (homebrew)
  community.general.homebrew:
    name: omnisharp-mono
  tags:
    - neovim
    - omnisharp
    - csharp

- name: Install Lua LSP (homebrew)
  community.general.homebrew:
    name: lua-language-server 
  tags:
    - neovim
    - omnisharp
    - csharp

- name: Install CSS Modules LS (npm)
  npm:
    name: cssmodules-language-server
    global: true
  tags:
    - neovim
    - css

