- name: Install node and npm (homebrew)
  community.general.homebrew:
    name: ['node', 'npm']
  tags:
  - node
  when: ansible_distribution == 'MacOSX'
- name: Install n (npm -g)
  npm:
    name: n
    global: true
  tags:
  - node
- name: Set node version (n 14)
  shell: n 14
  become: yes
  tags:
  - node
- name: Install tldr (npm -g)
  npm:
    name: tldr
    global: true
  tags:
  - tldr
  - node
- name: Install node and npm (homebrew)
  community.general.homebrew:
    name: yarn
  tags:
  - node
  - yarn 
